coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto 
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: auto
        base: auto
        if_ci_failed: error
        threshold: 5%

comment:
  require_changes: true
