# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: Codecov workflow
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.github/**'
      - 'codecov.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.github/**'
      - 'codecov.yml'
env:
  TEST_HOST: ${{ secrets.TEST_HOST }}
  TEST_FROM: ${{ secrets.TEST_USER }}
  TEST_ALLOW_SEND: "1"
  TEST_SMTPAUTH_USER: ${{ secrets.TEST_USER }}
  TEST_SMTPAUTH_PASS: ${{ secrets.TEST_PASS }}
  TEST_SMTPAUTH_TYPE: "LOGIN"
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.16, 1.17, 1.18, 1.19, 1.20]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Install sendmail
      if: matrix.go == 1.20 && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -y install sendmail; which sendmail
    - name: Run Tests
      run: |
        go test -v -race --coverprofile=coverage.coverprofile --covermode=atomic ./...
    - name: Upload coverage to Codecov
      if: success() && matrix.go == 1.20 && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
