# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check
on:
  push:
    branches:
      - main # or the name of your main branch
uses: fsfe/reuse-action@v1.1.1
